### PR TITLE
Fix and Refactoring repalceImage

### PR DESCRIPTION
**Pull request by k2la**
## WHY

To replace pod's image, kubedeploy uses execOuput function. 
## WHAT

It uses API client.

### CODE REVIEW

**Comment by dtan4** [comment]
Hmm, there is still point calling `kubectl` ...

``` bash
$ ag exec
replace.go
8:      "os/exec"
28:     result := execOutput("kubectl", commandOptions)
43:     _, err := exec.Command("kubectl", commandOptions...).Output()
```

Please remove all dependencies of `kubectl`, use native API client insread.

**Comment by k2la** [comment]
I removed execOutput function and fixed replaceColor function.

**Comment by dtan4** [comment]
Good. 

Finally, please remove `kubedeploy` from Docker image (= `Dockerfile`).

**Comment by k2la** [comment]
Do you mean `kubectl` ?

**Comment by dtan4** [comment]
> Do you mean kubectl ?

Oops.......... It's my mistake :trollface:

**Comment by k2la** [comment]
I removed commands about `kubectl`.

**Comment by dtan4** [comment]
LGTM 👍

**Pull request merged**
